### ISSUE TITLE
Consistent Sleep Crashing

### ISSUE THREAD

**Issue by xiaoschannel** [OndraSter/BetterSleeping#41]
Crash when sleeping on a bed, With forge 1987 and 1.9.4 gamma 7.

java.lang.IllegalArgumentException: There is no such day in this month!
    at foxie.calendar.implementation.CalendarImpl.setDay(CalendarImpl.java:99)
    at foxie.bettersleeping.modules.TirednessModule.onWorldSleepPre(TirednessModule.java:177)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_42_TirednessModule_onWorldSleepPre_Pre.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at foxie.bettersleeping.core.BSEvents.getSleepingTime(BSEvents.java:32)
    at foxie.bettersleeping.modules.TirednessModule.onWorldTick(TirednessModule.java:153)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_41_TirednessModule_onWorldTick_WorldTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:275)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:692)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:461)
    at java.lang.Thread.run(Thread.java:745)

**Comment by CallMeFoxie** [comment]
Should be fixed with https://github.com/CallMeFoxie/BetterSleeping2/commit/eb03d9dd4783d8dcbae330c7f84c5ac8c9251998
